### ISSUE TITLE
Add a filter to the partioning algorithm

### ISSUE THREAD

**Issue by fmaussion** [OGGM/partitioning#6]
Hi @juliaeis , I've been playing a little bit with the divides you provided me a couple of weeks ago. The algorithm now works very nicely, and I am building methods in OGGM so that it can deal with the many situations that arise. 

I think however that it would be good to limit the number of divides so that only the most important ones are kept. I've looked at a couple of glaciers and came up with simple filter rules that removed some divides without being to aggressive:
- keep a divide only if it's area is not smaller than 2% **of the largest divide**. This latter condition is important: that way the ice caps with many divides of comparable sizes (like RGI50-05.08389) are not filtered as strongly as a large valley glaciers with many irrelevant small divides (like RGI50-14.07524).
- keep a divide only if the **altitude range** of the divide is larger than 10% of the glaciers total altitude range 
- keep a divide only if the absolute **altitude range** of the divide is larger than 100m

These  thresholds worked well for the few glaciers I looked at, but this is arbitrary of course.

If any of this conditions is true, ignore the divide. I have a working code which does this (pasted below), but the problem I have is when I want to merge the filtered divides *back* to the original shape. I get into all kinds of possible issues with the geometries, which I think can be avoided if this filtering happens in the partitioning algorithm (maybe even at the raster level?).

The code I used:

```python
def filter_divides(gdir):
    """This filters out "bad" or undesired divides out of the set chosen by
    the divide algorithm.
    """

    global div_gdfs

    # Take the divides out of the original file
    div_gdf = cfg.PARAMS['divides_gdf']
    if gdir.rgi_id not in div_gdf.index.values:
        raise RuntimeError('We should have divides for this glacier')
    div_gdf = div_gdf.loc[gdir.rgi_id].copy()

    # OGGM sorts them by area, so let's do the same
    # Reproject first
    def proj(lon, lat):
        return salem.transform_proj(salem.wgs84, gdir.grid.proj,
                                    lon, lat)

    geoms = [shapely.ops.transform(proj, g) for g in div_gdf.geometry]
    div_gdf['Area'] = [g.area for g in geoms]
    div_gdf = div_gdf.sort_values('Area', ascending=False)
    div_gdf = div_gdf.reset_index()

    # Compute some stuff and make a decision based on this
    div_gdf['Perc_Area'] = div_gdf.Area / div_gdf.loc[0].Area

    alt_range = []
    for div_id in gdir.divide_ids:
        fpath = gdir.get_filepath('gridded_data', div_id=div_id)
        with netCDF4.Dataset(fpath) as nc:
            topo = nc.variables['topo_smoothed'][:]
            glacier_mask = nc.variables['glacier_mask'][:]
            topo = topo[np.where(glacier_mask)]
        alt_range.append(np.max(topo) - np.min(topo))

    div_gdf['Alt_Range'] = alt_range
    div_gdf['Perc_Alt_Range'] = alt_range / np.max(alt_range)

    # OK, div_gdf is what we want to filter
    # Conditions (arbitrary)
    nokeep = ((div_gdf['Perc_Alt_Range'] < 0.1) | (div_gdf['Alt_Range'] < 100))
    nokeep = nokeep | (div_gdf['Perc_Area'] < 0.02)
    div_gdf['keep'] = ~ nokeep

    # Filtered!
    print('We keep {} divides out of {} '
          'after filtering.'.format(np.sum(div_gdf['keep']),
                                    len(div_gdf)))

    # Now we have to merge back the filtered ones to the closest geometries
    # Firs clean the geometries of possible
    if np.sum(div_gdf['keep']) == 1:
        # Nothing to do! The divide should be ignored
        return

    while not np.all(div_gdf['keep']):
        geom = div_gdf.loc[~div_gdf['keep']].iloc[0]
        div_gdf = div_gdf.drop(geom.name)

        # In an ideal world there would be just one intersection.
        # Since we note sure this will always be the case, just take the
        # biggest common geometry
        inter_gdf = div_gdf.copy()
        inter_gdf['geometry'] = [g.buffer(0) for g in div_gdf.geometry]
        inter = inter_gdf.intersection(geom.geometry)
        idm = np.argmax(inter.length)
        assert np.max(inter.length) > 0
        big_geom = div_gdf.loc[idm]

        # @Julia: the union is not always perfect (i.e. RGI50-14.15990).
        # Any idea why? Maybe the transform back and forth of the projection?
        # This is why this logic should happen in your code, not mine
        union = big_geom.geometry.buffer(0).union(geom.geometry.buffer(0))
        assert type(union) is shpg.Polygon
        # Back in the dataframe
        div_gdf.loc[big_geom.name, 'geometry'] = union.buffer(0)

    # This is the final dataframe!
    del div_gdf['keep']
    div_gdfs.append(div_gdf)
```

**Comment by fmaussion** [comment]
After thinking about it a bit longer, maybe the first condition (size) is not that good.

What's really important is the altitude range thing: how large of a difference will it make if a flowline has to "climb up" the mountain?

**Comment by juliaeis** [comment]
I will put the last two conditions in the code. This should be no problem. 
The best way to merge the filtered divides is to treat them as sliver polygons. This means, that they will be merged to the divide with the longest shared boundary. 
Do you have a list of some glaciers, where the number of divides will be reduced by one of the last conditions? Then I would already have some test cases :)

**Comment by fmaussion** [comment]
> I will put the last two conditions in the code. This should be no problem.

Can you put all three, and add a top level option to test them? This would be great! ;-)

> The best way to merge the filtered divides is to treat them as sliver polygons. This means, that they will be merged to the divide with the longest shared boundary.

yes, this is how I did it (I think) but the merge wasn't always perfect (broken polygons). I think you know better than me how to do this.

> Do you have a list of some glaciers, where the number of divides will be reduced by one of the last conditions? Then I would already have some test cases :)

I have looked at four glaciers so far, and with all three options (didn't test the last two only so far):
- 'RGI50-14.15990', which would be better with two divides instead of three
- 'RGI50-14.07524', which is not divided anymore with the new filters (this one I'm not sure if this is good or not, at least one of the divides is quite useful)
- 'RGI50-11.00897' should not be changed by the filter, the divides are perfect
- 'RGI50-05.08389', where the filter removes one divide and keeps all the other ones

Thanks! No hurry

**Comment by juliaeis** [comment]
I have add the filter method and added a top level option. 
If filter_area, filter_alt_range and/or filter_perc_alt_range are set on True, the corresponding divides will be filtered out. Per default filer_area is False and the two other True.

**Comment by fmaussion** [comment]
This is great thanks! Could you send me the new divides when you have time? Currently the four glaciers above should be enough
